### ISSUE TITLE
Hello 😁

### ISSUE THREAD

**Issue by kirkyb** [linuxforphp/flarelinux#1]
Not an issue, but a hello instead 👍

**Comment by andrewscaya** [comment]
Hello to you too, @kirkyb ! 💯 

And, welcome! 👍

**Comment by andrewscaya** [comment]
To all those that are looking for our Slack channel, please visit [https://linuxforphp.net](https://linuxforphp.net), and click on the Slack invitation link. The #flare-linux channel is specifically dedicated to the creation of these Docker images.

Welcome to all! :)

/cc @kirkyb
